def on_b_pressed():
    global myEnemy, otherSprite2
    mySprite.set_flag(SpriteFlag.INVISIBLE, True)
    mySprite2.set_flag(SpriteFlag.INVISIBLE, True)
    info.start_countdown(60)
    info.set_life(1)
    scene.set_background_color(3)
    myEnemy = sprites.create(img("""
            ........................
            ......ffff..............
            ....fff22fff............
            ...fff2222fff...........
            ..fffeeeeeefff..........
            ..ffe222222eef..........
            ..fe2ffffff2ef..........
            ..ffffeeeeffff..........
            .ffefbf44fbfeff.........
            .fee41fddf14eef.........
            fdfeeddddd4eff..........
            fbffee444edd4e..........
            fbf4f2222edde...........
            fcf.f22cccee............
            .ff.f44cdc4f............
            ....fffddcff............
            .....fddcff.............
            ....cddc................
            ....cdc.................
            ....cc..................
            ........................
            ........................
            ........................
            ........................
            """),
        SpriteKind.player)
    otherSprite2 = sprites.create(img("""
            . . . . f f f f . . . .
            . . f f e e e e f f . .
            . f f e e e e e e f f .
            f f f f 4 e e e f f f f
            f f f 4 4 4 e e f f f f
            f f f 4 4 4 4 e e f f f
            f 4 e 4 4 4 4 4 4 e 4 f
            f 4 4 f f 4 4 f f 4 4 f
            f e 4 d d d d d d 4 e f
            . f e d d b b d d e f .
            . f f e 4 4 4 4 e f f .
            e 4 f b 1 1 1 1 b f 4 e
            4 d f 1 1 1 1 1 1 f d 4
            4 4 f 6 6 6 6 6 6 f 4 4
            . . . f f f f f f . . .
            . . . f f . . f f . . .
            """),
        SpriteKind.player)
    myEnemy.set_position(11, 11)
    myEnemy.follow(otherSprite2, 50)
    otherSprite2.set_position(143, 101)
    controller.move_sprite(otherSprite2)
    otherSprite2.set_stay_in_screen(True)
controller.B.on_event(ControllerButtonEvent.PRESSED, on_b_pressed)

def on_countdown_end():
    game.splash("You have passed level 1 but Ready for level 2.To unlock press 'z+x' ")
info.on_countdown_end(on_countdown_end)

def on_on_overlap(sprite, otherSprite):
    game.game_over(False)
sprites.on_overlap(SpriteKind.player, SpriteKind.player, on_on_overlap)

otherSprite2: Sprite = None
myEnemy: Sprite = None
mySprite2: Sprite = None
mySprite: Sprite = None
game.splash("press 'z'to play this game")
info.start_countdown(30)
info.set_life(1)
scene.set_background_color(9)
mySprite = sprites.create(img("""
        ......ffff..............
        ....fff22fff............
        ...fff2222fff...........
        ..fffeeeeeefff..........
        ..ffe222222eef..........
        ..fe2ffffff2ef..........
        ..ffffeeeeffff......ccc.
        .ffefbf44fbfeff....cddc.
        .ffefbf44fbfeff...cddc..
        .fee4dddddd4eef.ccddc...
        fdfeeddddd4eeffecddc....
        fbffee4444ee4fddccc.....
        fbf4f222222f1edde.......
        fcf.f222222f44ee........
        .ff.f445544f............
        ....ffffffff............
        .....ff..ff.............
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        """),
    SpriteKind.player)
mySprite2 = sprites.create(img("""
        . . . . f f f f . . . . .
        . . f f f f f f f f . . .
        . f f f f f f c f f f . .
        f f f f f f c c f f f c .
        f f f c f f f f f f f c .
        c c c f f f e e f f c c .
        f f f f f e e f f c c f .
        f f f b f e e f b f f f .
        . f 4 1 f 4 4 f 1 4 f . .
        . f e 4 4 4 4 4 4 e f . .
        . f f f e e e e f f f . .
        f e f b 7 7 7 7 b f e f .
        e 4 f 7 7 7 7 7 7 f 4 e .
        e e f 6 6 6 6 6 6 f e e .
        . . . f f f f f f . . . .
        . . . f f . . f f . . . .
        """),
    SpriteKind.player)
mySprite.set_position(155, -3)
mySprite.follow(mySprite2, 30)
mySprite2.set_position(-3, 113)
controller.move_sprite(mySprite2)
mySprite2.set_stay_in_screen(True)